2018-05-28 20:06:10,707 ERROR: Exception on /explore [GET] [in /home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jack/gitStore/microblog/app/routes.py", line 154, in explore
    next_url=next_url, prev_url=prev_url)
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jack/gitStore/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/jack/gitStore/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/jack/gitStore/microblog/app/templates/base.html", line 52, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/jack/gitStore/microblog/app/templates/index.html", line 20, in block "app_content"
    {% include '_post.html' %}
  File "/home/jack/gitStore/microblog/app/templates/_post.html", line 14, in top-level template code
    {{ _('%(username)s said %(when)s', username=user_link, when=moment(post.timestamp).fromNow()) }}:
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/jinja2/ext.py", line 134, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/jinja2/ext.py", line 140, in gettext
    rv = __context.call(func, __string)
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask_babel/__init__.py", line 116, in <lambda>
    lambda x: get_translations().ugettext(x),
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask_babel/__init__.py", line 227, in get_translations
    [get_locale()],
  File "/home/jack/.local/share/virtualenvs/microblog-bjOLqTYM/lib/python3.6/site-packages/flask_babel/__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "/home/jack/gitStore/microblog/app/__init__.py", line 58, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'request' is not defined
